### ISSUE TITLE
Doesn't work if file is not in CWD

### ISSUE THREAD

**Issue by jdoe0** [directorscut82/find_subtitles#5]
The script tries to load the subtitle file by parsing the output of `ls -a`, which gives the list of files in CWD. However, the `subliminal` command in line 22 will put the subtitle file(s) in the same directory as the playing file, so if the file is not in CWD, the script will not be able to find the subtitle.

**Comment by directorscut82** [comment]
Thank you & are absltl right.. Strangely i havent notice cause my tclient always defaults cwd to where i downloaded my movie(s) ...
Also i cannot test it right now because mpv refuse to work with my (newly installed) ubuntu 15.10+oibaf gdrivers, but if you
replace
`for filename in io.popen('ls -a'):lines()` 
with 
`for filename in io.popen('ls -a "'..mp.get_property("path")..'"'):lines()`
it would probably work...
(i will patch it when i manage to make mpv happy again..)

**Comment by directorscut82** [comment]
It was actually a bit more involved from what i proposed above, but now it is working irrespective the cwd
